import Head from 'next/head';
import type { NextPage } from 'next';
import styles from '../../styles/Home.module.css';
import LanguageSelection from '../../src/components/LanguageSelection/LanguageSelection';
import LogoButton from '../../src/components/LogoButton/LogoButton';
import Image from 'next/image';
import SkillsCard from '../../src/components/SkillsCard/SkillsCard';

const skills = [
  {
    id: 1,
    image:'/code-solid.svg',
    title: 'Front-end',
    description: 'O primeiro contato com o Front-end, foi com aquele HTML, CSS e Javascript básico, porém fundamental!',
    technologies: 'HTML, CSS, Javascript, React, Next.JS, Tailwind',
    devTools: 'Git, Codepen, VSCode, Terminal'
  },
  {
    id: 2,
    image:'/terminal-solid.svg',
    title: 'Back-end',
    description: 'O Back-end na minha vida se desenvolveu junto com a minha curiosidade, buscando formas de entender e construir aplicações próprias.',
    technologies: 'NodeJS, NestJS, MySQL',
    devTools: 'Git, Insomnia, Workbench, VSCode, Terminal'
  }
];

const Home: NextPage = (language) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfólio - Felipe Henrique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <LogoButton />
        <LanguageSelection language="PT-BR" />
      </header>

      <main className={styles.main}>
        <h1 className={styles.person_title}>Desenvolvedor Full-stack</h1>
        <h4 className={styles.person_subtitle}>Gosto de deasfios e sempre busco aprender algo novo. O aprendizado nunca para!</h4>
        <div>
          <Image
            width="350"
            height="350"
            src="/foto-perfil.jpg"
            className={styles.person_photo}
          />
        </div>
        <div className={styles.background}>
          <Image
            width="500"
            height="200"
            src="/banner-featured.png"
          />
        </div>
        <section className={styles.intro_section}>
          <h1>Oi, meu nome é Felipe. Prazer em te conhecer!</h1>
          <p>
            Desde pequeno interessado em computador e jogos, decidi
            buscar algo que me aproximasse dessa area. Em 2015, iniciei
            o curso de Ciência da Computação que ainda não conclui, mas
            que serviu em muitas coisas importantes e uma delas foi a minha
            cabeça em relação ao que poderia fazer.
            Foi em uma matéria que me apaixonei por Javascript e tudo que rodeava
            essa linguagem de programação. Há dois anos estudo e trabalho com essa
            linguagem e pretendo me especializar nela.
          </p>
        </section>
        <section className={styles.skills_section}>
          {skills.map((skill) =>
            <SkillsCard
              key={skill.id}
              image={skill.image}
              title={skill.title}
              description={skill.description}
              technologies={skill.technologies}
              devTools={skill.devTools}
            />
          )}
        </section>

        <section className={styles.social_section}>
            <h1>Minhas redes sociais</h1>
        </section>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
