import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfólio - Felipe Henrique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav>
          <ul>
            <li>Sobre mim</li>
            <li>Experiências</li>
            <li>Habilidades Técnicas</li>
            <li>Contato</li>
          </ul>
          <div>
            <p>ícone</p>
          </div>
        </nav>
      </header>

      <main className={styles.main}>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
